### ISSUE TITLE
Usability issues, "space", disabled etc

### ISSUE THREAD

**Issue by RichColours** [jerosa/spotify-hotkeys-firefox#19]
Hi there

Thank you so much for this hotkey tool 😺  It's working pretty well - I want to help make it better!

So, i've installed this just five minutes ago. Latest firefox on MBP.

* How do I set "space"? If i put in a space ' ' char then on focus leave the previous value is put back. Typing in 'space' or 'Space' is not helping either.
* Can we disable individual actions? Just leaving an entry blank, say on 'save track' just means that on focus leave the old value is put back in.
* We can see that if you install this afresh, there is left and right arrows in the net and previous boxes. If you put your own in then want to put arrow back, how would I know to type the '→' in? In your wiki you've just got the word "arrows" not actual arrows. I think your docs could be more accurate here.

Hope you can help! Let me know about the space one cus i want my keys to be the same as Youtube. J L, 'space'.

Rich

**Comment by RichColours** [comment]
Oh I've just found the "Manage extention shortcuts" page in the little cog of the extention.

What is this screen used for?

![image](https://user-images.githubusercontent.com/13033494/91843563-dea1bd00-ec4d-11ea-8947-f5afeb62f06a.png)

**Comment by jerosa** [comment]
Heya!

I'm glad you like it and feel free to participate!
I will try to answer the questions in order, but not without first making a clarification. There are two ways to customize the shortcuts, one old and obsolete way is the one you show in the screenshot and ask the questions about and the other way is the "official" one they implemented in Firefox not long ago.

**PREFERENCES TAB (deprecated)**

- You can't use the space key as a shortcut
- You can't disable shortcuts
- In order to use the arrows as a shortcut you must write the direction of the arrow (left, right, up, down) and it will appear. The documentation is not very clear, certainly.


**Manage extention shortcuts (official)**

- You can assign the space key as a shortcut but with CTRL or ALT as modifiers.
- It is possible to disable certain actions from there using the paper bin icon.
- In this case it is enough to press the keys that you want to use as shortcuts.

Having said all this, perhaps it is best to remove the old method that has its limitations as there is now an official way to customize keyboard shortcuts.

**Comment by jerosa** [comment]
Updated the docs with the more info about changing the shortcuts with the "official way"
